spring:
  datasource:
    url: ${DB_URL}
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: false
  jpa:
    defer-datasource-initialization: false
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    url: ${DB_URL}
    user: test
    password: test
    baseline-on-migrate: true